### ISSUE TITLE
Add microphone support for music synced led animations

### ISSUE THREAD

**Issue by marksev1** [sticilface/Melvanimate#10]
Please add microphone support for music synced led animations - like this: https://learn.adafruit.com/led-ampli-tie/overview

**Comment by sticilface** [comment]
This has been on the cards... just not sure what the best way is, or how good it would be.  
The ADC on the ESP8266 only measures up to 1V so there are some hardware issues... 
Will try though

**Comment by wutu** [comment]
+1

**Comment by marksev1** [comment]
Awesome :-)

**Comment by sticilface** [comment]
EQ support will arrive.. I have finally... got an MSGEQ7 chip working with an arduino, and now working beautifully with Melvanimate in the form of a graphic equaliser on ESP8266.  so there will be more to come!   The reason i struggled so much was that I had 3 faulty MSGEQ7 chips, which has been a total nightmare.  I've been working or trying to work with this for over a year!  Only debugging with an osillyscope solved everything. 

Support for microphone might not happen... I've tried one, with integrated amp and it is rubbish.  Line in though works like a treat.  This has been an epic.. to get working.. i was concerned about time to acquire the signal too, but i've got it down to 600us, and that is entirely due to the time it takes to do 7 analoguereads.  

![file 07-04-2016](https://cloud.githubusercontent.com/assets/10061736/14356549/3925b5e8-fcdd-11e5-9cba-d3be1e5cefba.jpeg)

![esp8266-msgeq7-first](https://cloud.githubusercontent.com/assets/10061736/14354823/afe7c51a-fcd6-11e5-87a6-b3d0af161f4b.png)

**Comment by marksev1** [comment]
So is this like very complicated to hook up :-)

**Comment by sticilface** [comment]
not particularly.  An MSGEQ7 and some caps + resistor

![screenshot 2016-04-10 16 56 21](https://cloud.githubusercontent.com/assets/10061736/14411343/31ac9a68-ff3d-11e5-8034-39f19ac0b69d.png)

**Comment by marksev1** [comment]
Very cool, hopefully you'll make some demo video :D

**Comment by marksev1** [comment]
sticilface whats that 74HCT245N used for?

**Comment by sticilface** [comment]
It's A logic level converter. That changes the esp 3.3V to 5V. Not found a smaller one that works, and this works perfectly so I've carried on using it.

**Comment by probonopd** [comment]
Is the logic level converter really needed given
http://www.ba0sh1.com/2016/08/03/is-esp8266-io-really-5v-tolerant/?

**Comment by sticilface** [comment]
the logic level converter is for neopixels... i found that it made a huge difference especially at low brightness... i would get flashes... with the logic level converter it works perfectly.  technically 3.3V is out of spec for the neopixels.

**Comment by probonopd** [comment]
I see

**Comment by sticilface** [comment]
this is done and working now
